---
- name: Influx repository key present
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Influx repository present
  apt_repository:
    repo: 'deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
    state: present

- name: Influx present
  apt:
    name: influxdb2
    state: present

- name: Influx restarted 
  service:
    name: influxdb2
    state: restarted

- name: Influx configured
  command: influx setup  --org {{ influxdb_org }} --bucket {{ influxdb_bucket }} --username {{ influxdb_user }} --password {{ influxdb_password }} --force --skip-verify
  ignore_errors: yes 

- name: Influx access token present
  command: influx auth create --org {{ influxdb_org }} --all-access

...
