---
- name: ensure https transport presents
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
    state: present

- name: Add a grafana signing key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add grafana specified repository into sources list
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: true

- name: Install grafana
  apt:
    name: grafana
    state: present

- name: Get token
  shell:  influx auth list |  awk 'NR==2 {print $4}'
  register: TOKEN

- name: Token to variable
  set_fact:
      influx_token: "{{ TOKEN.stdout }}"

- debug:
   var: influx_token

- name: Prep provisoning datasources
  template:
    src: datasource.yaml.j2
    dest: "/etc/grafana/provisioning/datasources/datasource.yaml"

- name: Prep dashboard provider
  template:
    src: provider.yaml.j2
    dest: "/etc/grafana/provisioning/dashboards/provider.yaml"

- name: Create dashboards directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards/
    state: directory

- name: Prep provisioning dashboard
  template:
   src: dashboard.json.j2
   dest: "/var/lib/grafana/dashboards/dashboard.json"
  notify: restart grafana
...
