---
- name: Https transport present
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
    state: present

- name: Grafana's repository key present
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Grafana's repository present
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: true

- name: Grafana present
  apt:
    name: grafana
    state: present

- name: Influx token captured
  shell:  influx auth list |  awk 'NR==2 {print $4}'
  register: TOKEN

- name: Influx token added to variables
  set_fact:
      influx_token: "{{ TOKEN.stdout }}"

- debug:
   var: influx_token

- name: Datasources configured
  template:
    src: datasource.yaml.j2
    dest: "/etc/grafana/provisioning/datasources/datasource.yaml"

- name: Dashboard provider configured
  template:
    src: provider.yaml.j2
    dest: "/etc/grafana/provisioning/dashboards/provider.yaml"

- name: Dashboard's directory insist
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards/
    state: directory

- name: Provisioning dashboard configured
  template:
   src: dashboard.json.j2
   dest: "/var/lib/grafana/dashboards/dashboard.json"
  notify: restart grafana
...
