---

#- name: Telegraf repository key present
#  apt-key:
#   url: https://repos.influxdata.com/influxdb.key
#   state: present

- name: Telegraf repository present
  apt_repository:
    repo: 'deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
    state: present

- name: Telegraf present
  apt:
   name: "telegraf{% if telegraf_version is defined %}={{ telegraf_version }}{% endif %}"
   state: present
   update_cache: true

- name: Influx token captured
  shell:  influx auth list |  awk 'NR==2 {print $4}' 
  register: TOKEN

- name: Influx token added to variables
  set_fact:
      influx_token: "{{ TOKEN.stdout }}"

- debug:
   var: influx_token

- name: Telegraf configured
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify:
    - restart telegraf 

...
